apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-service
  namespace: prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: { app: batch-service }
  template:
    metadata:
      labels: { app: batch-service }
    spec:
      containers:
        - name: batch-service
          image: nohyunha95/batch-service:0.0.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          envFrom:
            - secretRef:
                name: batch-service-secrets
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8090 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8090 }
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: batch-service
  namespace: prod
spec:
  selector: { app: batch-service }
  ports:
    - port: 8090
      targetPort: 8090
  type: ClusterIP
