apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: prod
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: { app: auth-service }
  template:
    metadata:
      labels: { app: auth-service }
    spec:
      containers:
        - name: auth-service
          image: nohyunha95/auth-service:0.0.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          envFrom:
            - secretRef:
                name: auth-service-secrets
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8081 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8081 }
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: prod
spec:
  selector: { app: auth-service }
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
