apiVersion: apps/v1
kind: Deployment
metadata:
  name: naming-server
  namespace: prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: { app: naming-server }
  template:
    metadata:
      labels: { app: naming-server }
    spec:
      containers:
        - name: naming-server
          image: nohyunha95/naming-server:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761

          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8761 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8761 }
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: naming-server
  namespace: prod
spec:
  selector: { app: naming-server }
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
